#SERVER PORT
server:
  port: 9006

#SPRING APPLICATION NAME
spring:
  devtools:
    restart:
      exclude: static/**,public/**

  #MULTIPART FILE CONFIGURATION
  servlet:
    multipart:
      max-file-size: 524288000
      max-request-size: 524288000

  #SPRING APPLICATION NAME
  application:
    name: dss4-ms-movie-v1

  #SPRING BEAN DEFINITION
  main:
    allow-bean-definition-overriding: true

  #SPRING DATASOURCE CONFIGURATION
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

  #JPA AND HIBERNATE PROPERTIES
  jpa:
    database: oracle
    properties:
      hibernate:
        jdbc:
          timezone: GMT+8
        dialect: org.hibernate.dialect.Oracle9iDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true

#SLF4J LOGBACK CONFIGURATION
logging:
  level:
    root: error
    org.springframework: debug
    org.hibernate: error

# REGISTER WITH EUREKA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

dss-file-path: C:\applogs\image\